version: '3.3'
services:
  api:
    build: .
    image: tapis/pgrest-api:dev
    command: bash -c "uwsgi --http :5000 --module paas.wsgi"
    volumes:
    - .:/code
    - ./config-local.json:/code/config-local.json
    - ./pgrest.log:/code/pgrest.log
    ports:
    - "5000:5000"
    environment:
      TAPIS_CONFIGSCHEMA_PATH: /code/pgrest/configschema.json
      TAPIS_CONFIG_PATH: /code/config-local.json
      #Uncomment to enable django debug --
      #PGREST_DEBUG: "true"
    depends_on:
      - db
    container_name: pgrest-api


  db:
    image: postgres:9.6.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"
    container_name: pgrest-postgres


volumes:
  postgres_data: